spring:
  application:
    name: product-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.40.198:8848
        fail-fast: false
        timeout: 5000
        watch-delay: 30000
        namespace: public
        management-port: ${server.port}
        metadata:
          management.port: ${server.port}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  zipkin:
    base-url: http://192.168.40.198:9411
  sleuth:
    sampler:
      probability: 1.0

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: tri
    port: ${DUBBO_PORT:50052}
  registry:
    address: nacos://192.168.40.198:8848
    parameters:
      namespace: public
  metrics:
    protocol: prometheus
    port: 20889
    enable-jvm: true

logging:
  level:
    root: INFO
    com.shop: DEBUG
