spring:
  cloud:
    gateway.server.webflux:
      httpclient:
        pool:
          max-connections: 1000
          acquire-timeout: 2000
      metrics:
        enabled: true
      # 开启网关从注册中心（Nacos）自动发现服务的能力
      discovery:
        locator:
          enabled: false
          lower-case-service-name: true # 允许使用小写服务名进行路由
      routes:
        - id: user_service_route
          uri: http://localhost:50051
          predicates:
            - Path=/api/user/**
        - id: product_service_route
          uri: http://localhost:50052
          predicates:
            - Path=/api/product/**
        - id: order_service_route
          uri: http://localhost:50053
          predicates:
            - Path=/api/order/**

logging:
  level:
    root: INFO
    com.shop.gateway: DEBUG
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG