spring:
  cloud:
    gateway.server.webflux:
      httpclient:
        pool:
          max-connections: 1000
          acquire-timeout: 2000
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: false
          lower-case-service-name: true
      routes:
        - id: user_service_route
          uri: http://localhost:50051
          predicates:
            - Path=/api/user/{segment}
          filters:
            - RewritePath=/api/user/(?<remaining>.*), /com.shop.dubbo.api.user.UserDubboService/${remaining}
        - id: product_service_route
          uri: http://localhost:50052
          predicates:
            - Path=/api/product/{segment}
          filters:
            - RewritePath=/api/product/(?<remaining>.*), /com.shop.dubbo.api.product.ProductDubboService/${remaining}
        - id: order_service_route
          uri: http://localhost:50053
          predicates:
            - Path=/api/order/{segment}
          filters:
            - RewritePath=/api/order/(?<remaining>.*), /com.shop.dubbo.api.order.ProductDubboService/${remaining}

logging:
  level:
    root: INFO
    com.shop: DEBUG
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG