spring:
  cloud:
    consul:
      host: 192.168.40.198
      port: 8500
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${server.port}:${random.value}
        prefer-ip-address: true
    gateway:
      httpclient:
        pool:
          max-connections: 1000
          acquire-timeout: 2000
      metrics:
        enabled: true
      # 开启网关从注册中心（Nacos）自动发现服务的能力
      discovery:
        locator:
          enabled: true
          lower-case-service-name: true # 允许使用小写服务名进行路由
      server:
        webflux:
          routes:
            - id: user_service_route
              uri: lb://user-service
              predicates:
                - Path=/api/user/**
            - id: product_service_route
              uri: lb://product-service
              predicates:
                - Path=/api/product/**
            - id: order_service_route
              uri: lb://order-service
              predicates:
                - Path=/api/order/**

logging:
  level:
    root: INFO
    com.shop.gateway: DEBUG
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG