spring:
  cloud:
    gateway.server.webflux:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: product_service_route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
        - id: order_service_route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
