spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.40.198:8848
        fail-fast: false
        timeout: 5000
        watch-delay: 30000
        namespace: public
  zipkin:
    base-url: http://192.168.40.198:9411
  sleuth:
    sampler:
      probability: 1.0

dubbo:
  application:
    name:  ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://192.168.40.198:8848
  consumer:
    check: false
    protocol: tri


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
