spring:
  datasource:
    url: jdbc:h2:mem:shop_order;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: 192.168.40.198
      port: 6379
  cloud:
    consul:
      host: 192.168.40.198
      port: 8500
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health # 网关提供健康检查的路径
        health-check-interval: 10s          # 每10秒检查一次
        instance-id: ${spring.application.name}:${server.port}:${random.value} # 保证分布式部署时实例 ID 唯一
        prefer-ip-address: true     # 推荐：注册时使用 IP 地址而不是计算机名，避免跨网络时解析不到
  kafka:
    bootstrap-servers: 192.168.40.198:9092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
