spring:
  application:
    name: order-service
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  zipkin:
    base-url: http://192.168.40.198:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8083

product-service:
  url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.shop: DEBUG
    org.springframework.web: INFO
